-- WINDOW SIZE
WINDOW_WIDTH = 1280;
WINDOW_HEIGHT = 720;

-- VIRTUAL SIZE
VIRTUAL_WIDTH = 432;
VIRTUAL_HEIGHT = 243;

-- PADDLE WIDTH
SMALL_PADDLE_WIDTH = 32;
MEDIUM_PADDLE_WIDTH = 64;
LARGE_PADDLE_WIDTH = 96;
MEGA_PADDLE_WIDTH = 128;

-- PADDLE HEIGHT
PADDLE_HEIGHT = 16;

-- NUMBER OF PADDLE SKINS = 3
NUM_OF_PADDLE = 3;

-- PADDLE SPEED
PADDLE_SPEED = 200;